'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.CareSummary

    Partial Public Class CareSummaryControl

        '''<summary>
        '''Div10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelCareSummaryInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCareSummaryInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSetting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSetting As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''UpdatePanelCareSummaryFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelCareSummaryFilter As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonViewError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonViewError As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelSearchByClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchByClient As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListSearchByClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListSearchByClient As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelPayPeriodCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPayPeriodCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListPayPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListPayPeriod As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SqlDataSourcePayPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourcePayPeriod As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''LabelContract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelContract As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListSearchByContract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListSearchByContract As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelTimeSheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTimeSheet As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ListBoxTimeSheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ListBoxTimeSheet As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''LabelBilled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelBilled As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ListBoxBilled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ListBoxBilled As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''ButtonClearFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClearFilter As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UpdatePanelCareSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelCareSummary As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldClientId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldClientId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldEmployeeId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldEmployeeId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldStartDate As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldEndDate As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldScheduleId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldScheduleId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''GridViewCareSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewCareSummary As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''UpdatePanelActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonRefresh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonRefresh As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonIndividualDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonIndividualDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonEmployeeDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonEmployeeDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonResetBatch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonResetBatch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonAdjust control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonAdjust As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UpdatePanelTotalAdjustedTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelTotalAdjustedTime As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''CheckBoxSavePrompt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBoxSavePrompt As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''LabelTotalAdjustedTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTotalAdjustedTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxTotalAdjustedTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxTotalAdjustedTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelTotalActualTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelTotalActualTime As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelTotalActualTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTotalActualTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxTotalAcutualTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxTotalAcutualTime As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
