'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.EDISubmission

    Partial Public Class EDISubmissionControl

        '''<summary>
        '''Div10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelEDISubmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEDISubmission As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SqlDataSourceDropDownListPlaceOfService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceDropDownListPlaceOfService As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''LabelViewRecords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelViewRecords As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelViewRecords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelViewRecords As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelPayPeriodStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPayPeriodStartDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelPayPeriodEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPayPeriodEndDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SqlDataSourcePayPeriodStartEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourcePayPeriodStartEndDate As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''LabelPayPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPayPeriod As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListPayPeriodStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListPayPeriodStartDate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListPayPeriodEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListPayPeriodEndDate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelContractNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelContractNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListContractNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListContractNumber As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SqlDataSourceContractInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceContractInfo As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''ButtonViewRecords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonViewRecords As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelFTPSend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFTPSend As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelFTPSend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelFTPSend As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUserName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListUserName As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ButtonFtpSend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonFtpSend As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPassword As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelFtpSite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFtpSite As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxFtpSite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFtpSite As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelDirectory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDirectory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxDirectory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxDirectory As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HyperLinkTexMedConnect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HyperLinkTexMedConnect As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''LabelViewFTP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelViewFTP As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelViewFTP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelViewFTP As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonPopulateListBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonPopulateListBox As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonClearList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClearList As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ListBoxNamesList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ListBoxNamesList As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''SqlDataSourceNamesList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceNamesList As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''LabelEDISubmissionDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEDISubmissionDetail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelEDISubmissionDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelEDISubmissionDetail As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldClientId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldClientId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''GridViewEDISubmissionDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewEDISubmissionDetail As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''LabelMiscAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMiscAction As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelResubmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelResubmission As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CheckBoxResubmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBoxResubmission As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''LabelComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelComment As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelSystemDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSystemDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSystemDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSystemDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelTotalBillAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTotalBillAmount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxTotalBillAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxTotalBillAmount As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonCorrectClaim control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonCorrectClaim As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonMissingData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonMissingData As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonRefresh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonRefresh As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonDeleteSubmissionList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonDeleteSubmissionList As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''TextBoxSaveLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSaveLocation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ButtonGenerate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonGenerate As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSubmissionReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSubmissionReport As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonIndividualBilling control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonIndividualBilling As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonIndividualDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonIndividualDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSubmissionInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSubmissionInfo As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
