'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.ClientInfo

    Partial Public Class AuthorizationDetailControl

        '''<summary>
        '''LabelAuthorizationDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAuthorizationDetail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelAuthorizationDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelAuthorizationDetail As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelAuthorizatioReceivedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAuthorizatioReceivedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAuthorizatioReceivedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAuthorizatioReceivedDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorAuthorizatioReceivedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorAuthorizatioReceivedDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''LabelPractitionerStatementReceivedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPractitionerStatementReceivedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPractitionerStatementReceivedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPractitionerStatementReceivedDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorPractitionerStatementReceivedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorPractitionerStatementReceivedDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''LabelPractitionerStatementSentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPractitionerStatementSentDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPractitionerStatementSentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPractitionerStatementSentDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorPractitionerStatementSentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorPractitionerStatementSentDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''LabelServiceInitializedReportedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelServiceInitializedReportedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxServiceInitializedReportedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxServiceInitializedReportedDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorServiceInitializedReportedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorServiceInitializedReportedDate As Global.System.Web.UI.WebControls.RegularExpressionValidator
    End Class
End Namespace
