'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.ClientInfo

    Partial Public Class BillingDiagnosisCodeControl

        '''<summary>
        '''LabelBillingDiagnosisCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelBillingDiagnosisCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelBillingDiagnosisCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelBillingDiagnosisCode As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''DropDownListBillingDiagnosisOne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListBillingDiagnosisOne As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListBillingDiagnosisCodeOne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListBillingDiagnosisCodeOne As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListBillingDiagnosisTwo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListBillingDiagnosisTwo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListBillingDiagnosisCodeTwo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListBillingDiagnosisCodeTwo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListBillingDiagnosisThree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListBillingDiagnosisThree As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListBillingDiagnosisCodeThree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListBillingDiagnosisCodeThree As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListBillingDiagnosisFour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListBillingDiagnosisFour As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListBillingDiagnosisCodeFour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListBillingDiagnosisCodeFour As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
