'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.ClientInfo

    Partial Public Class CaseInformationControl

        '''<summary>
        '''Div16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div16 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelCaseInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCaseInformation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSettingCaseInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingCaseInformation As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''LabelCaseInformationCaseWorker control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCaseInformationCaseWorker As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelCaseInformationEmployee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCaseInformationEmployee As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelCaseInformationDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCaseInformationDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelCaseInformationReceiverOrganization control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCaseInformationReceiverOrganization As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelCaseInformationUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCaseInformationUpdateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelCaseInformationUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCaseInformationUpdateBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelCaseInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelCaseInformation As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldCaseInfoId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldCaseInfoId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''PlaceHolderCaseInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolderCaseInformation As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''UpdatePanelCaseInfoActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelCaseInfoActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonFaxCoverPageReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonFaxCoverPageReport As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonOpenReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonOpenReport As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonCaseInformationClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonCaseInformationClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonCaseInformationSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonCaseInformationSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonCaseInformationDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonCaseInformationDelete As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
