'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.ClientInfo

    Partial Public Class ClientCalendarControl

        '''<summary>
        '''Div15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div15 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelWeeklyCalendar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelWeeklyCalendar As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSettingWeeklyCalendar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingWeeklyCalendar As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''UpdatePanelCalendarInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelCalendarInfo As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonActiveOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonActiveOnly As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonInActiveOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonInActiveOnly As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonAll As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelClientStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelClientStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListSearchByScheduleStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListSearchByScheduleStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelHoursMinutesCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelHoursMinutesCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelEmployeeCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEmployeeCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelSunday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSunday As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelMonday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMonday As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelTuesday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTuesday As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelWednesday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelWednesday As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelThursday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelThursday As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelFriday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFriday As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelSaturday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSaturday As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelScheduleUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelScheduleUpdateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelScheduleUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelScheduleUpdateBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelDetailInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDetailInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelWeeklyCalendar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelWeeklyCalendar As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''PlaceHolderCalendarSetting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolderCalendarSetting As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''ButtonClearSchedule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClearSchedule As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSaveSchedule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSaveSchedule As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonEmployeeDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonEmployeeDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UpdatePanelScheduleHiddenFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelScheduleHiddenFields As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldScheduleId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldScheduleId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldEmployeeDetailId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldEmployeeDetailId As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
