'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.ClientInfo

    Partial Public Class ClientCommentsControl

        '''<summary>
        '''LabelTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSettingClientComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingClientComments As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''UpdatePanelComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelComments As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''MainDiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MainDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''UpdatePanelClientCommentActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelClientCommentActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldCommentId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldCommentId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldCommentIsNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldCommentIsNew As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldCommentIndex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldCommentIndex As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ButtonClearComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClearComment As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonCommunicationNotesComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonCommunicationNotesComment As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSaveComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSaveComment As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonDeleteComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonDeleteComment As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
