'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.ClientInfo

    Partial Public Class CurrentAuthorizationPeriodControl

        '''<summary>
        '''LabelAuthorization control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAuthorization As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelAuthorization control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelAuthorization As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelAuthorizationFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAuthorizationFromDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAuthorizationFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAuthorizationFromDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorAuthorizationFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorAuthorizationFromDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''LabelAuthorizationToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAuthorizationToDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAuthorizationToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAuthorizationToDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorAuthorizationToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorAuthorizationToDate As Global.System.Web.UI.WebControls.RegularExpressionValidator
    End Class
End Namespace
