'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.ClientInfo

    Partial Public Class EVVControl

        '''<summary>
        '''LabelEVV control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEVV As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelEVV control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelEVV As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelEVVClientId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEVVClientId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEVVClientId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEVVClientId As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelEVVARNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEVVARNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEVVARNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEVVARNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelEVVPriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEVVPriority As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListEVVPriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListEVVPriority As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelEVVBillCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEVVBillCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEVVBillCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEVVBillCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelEVVProcCodeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEVVProcCodeQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEVVProcCodeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEVVProcCodeQualifier As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelEVVLandPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEVVLandPhone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEVVLandPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEVVLandPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorEVVLandPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorEVVLandPhone As Global.System.Web.UI.WebControls.RegularExpressionValidator
    End Class
End Namespace
