'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.ClientInfo

    Partial Public Class EVVInfoControl

        '''<summary>
        '''LabelEVVInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEVVInformation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelEVVInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelEVVInformation As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelProgramOrService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelProgramOrService As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelServiceGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelServiceGroup As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelServiceCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelServiceCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelServiceCodeDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelServiceCodeDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelHCPCS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelHCPCS As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelModifiers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelModifiers As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListProgramOrService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListProgramOrService As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListServiceGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListServiceGroup As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListServiceCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListServiceCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListServiceCodeDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListServiceCodeDescription As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''TextBoxHCPCS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxHCPCS As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxModifierOne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxModifierOne As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxModifierTwo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxModifierTwo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxModifierThree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxModifierThree As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxModifierFour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxModifierFour As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
