'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.ClientInfo

    Partial Public Class IndividualInformationControl

        '''<summary>
        '''Div11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div11 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelClientInformationEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelClientInformationEntry As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSettingClientInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingClientInfo As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''LabelIndividualStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelIndividualStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListIndividualStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListIndividualStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LinkButtonAddMoreIndividualStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinkButtonAddMoreIndividualStatus As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''Image9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image9 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''LabelSupervisor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSupervisor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSupervisor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSupervisor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSupervisorVisitFrequency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSupervisorVisitFrequency As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSupervisorVisitFrequency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSupervisorVisitFrequency As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelAssessmentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAssessmentDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAssessmentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAssessmentDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorAssessmentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorAssessmentDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''LabelLiaison control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelLiaison As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxLiaison control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxLiaison As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelClientInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelClientInformation As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelStateClientId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelStateClientId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxStateClientId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxStateClientId As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelInsuranceNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelInsuranceNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxInsuranceNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxInsuranceNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFirstName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelMiddleInitial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMiddleInitial As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxMiddleInitial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxMiddleInitial As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelLastName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelCounty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCounty As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListCounty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListCounty As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LinkButtonAddMoreCounty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinkButtonAddMoreCounty As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''Image7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image7 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''LabelAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelApartmentNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelApartmentNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxApartmentNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxApartmentNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListCity As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LinkButtonAddMoreCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinkButtonAddMoreCity As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''Image5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''LabelState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListState As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LinkButtonAddMoreState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinkButtonAddMoreState As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''LabelZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelZip As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxZip As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPhone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorPhone As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''LabelAlternatePhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAlternatePhone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAlternatePhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAlternatePhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorAlternatePhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorAlternatePhone As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''LabelDateOfBirth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDateOfBirth As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxDateOfBirth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxDateOfBirth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorDateOfBirth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorDateOfBirth As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''LabelAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAge As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAge As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSocialSecurityNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSocialSecurityNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSocialSecurityNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSocialSecurityNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorSocialSecurityNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorSocialSecurityNumber As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''LabelGender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelGender As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListGender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListGender As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelMaritalStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMaritalStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListMaritalStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListMaritalStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelServiceStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelServiceStartDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxServiceStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxServiceStartDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorStartDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''LabelServiceEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelServiceEndDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxServiceEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxServiceEndDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidatorEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorEndDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''ucIndividualOtherInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucIndividualOtherInformation As Global.VisitelWeb.Visitel.UserControl.ClientInfo.IndividualOtherInformationControl

        '''<summary>
        '''ucEmergencyContract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucEmergencyContract As Global.VisitelWeb.Visitel.UserControl.ClientInfo.EmergencyContractControl

        '''<summary>
        '''ucCurrentAuthorizationPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucCurrentAuthorizationPeriod As Global.VisitelWeb.Visitel.UserControl.ClientInfo.CurrentAuthorizationPeriodControl

        '''<summary>
        '''ucBillingInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucBillingInfo As Global.VisitelWeb.Visitel.UserControl.ClientInfo.BillingInfoControl

        '''<summary>
        '''ucEVV control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucEVV As Global.VisitelWeb.Visitel.UserControl.ClientInfo.EVVControl

        '''<summary>
        '''ucBillingDiagnosisCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucBillingDiagnosisCode As Global.VisitelWeb.Visitel.UserControl.ClientInfo.BillingDiagnosisCodeControl

        '''<summary>
        '''ucAuthorizationDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucAuthorizationDetail As Global.VisitelWeb.Visitel.UserControl.ClientInfo.AuthorizationDetailControl

        '''<summary>
        '''ucEVVInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucEVVInfo As Global.VisitelWeb.Visitel.UserControl.ClientInfo.EVVInfoControl

        '''<summary>
        '''ucService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucService As Global.VisitelWeb.Visitel.UserControl.ClientInfo.ServiceControl

        '''<summary>
        '''UpdatePanelActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonCoordinationOfCare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonCoordinationOfCare As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonHealthAssessOrSDP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonHealthAssessOrSDP As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSupVisit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSupVisit As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonMapquest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonMapquest As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonDelete As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSynchronizeDiagnosisCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSynchronizeDiagnosisCode As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonIndividualDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonIndividualDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonBillingInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonBillingInformation As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UpdatePanelHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelHiddenField As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldClientInfoId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldClientInfoId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsNew As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsSearched control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsSearched As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIndividualStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIndividualStatus As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
