'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.ClientInfo

    Partial Public Class TasksControl

        '''<summary>
        '''UpdatePanelTasks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelTasks As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelTasks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTasks As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSettingTasks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingTasks As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''CheckBathing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBathing As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckLaundry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckLaundry As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckMealPreparation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckMealPreparation As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckDressing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckDressing As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckToileting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckToileting As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckEscort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckEscort As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckExcercisng control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckExcercisng As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckTransfer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckTransfer As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckAmbulation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckAmbulation As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckShopping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckShopping As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckFeeding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckFeeding As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckCleaning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckCleaning As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckAsst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckAsst As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckGrooming control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckGrooming As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckHairSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckHairSkin As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckWalking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckWalking As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckOther As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''TextOtherSpec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextOtherSpec As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelTasksUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTasksUpdateBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextTasksUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextTasksUpdateBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelTasksUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTasksUpdateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextTasksUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextTasksUpdateDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HiddenFieldTaskId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldTaskId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldTasksIsNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldTasksIsNew As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''UpdatePanelActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonClearTasks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClearTasks As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSaveTasks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSaveTasks As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonDeleteTasks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonDeleteTasks As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
