'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.EVV

    Partial Public Class MEDsysStaffsControl

        '''<summary>
        '''Div10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelMEDsysStaffs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMEDsysStaffs As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSetting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSetting As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''ButtonViewError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonViewError As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UpdatePanelGridViewMEDsysStaffs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelGridViewMEDsysStaffs As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldEmployeeId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldEmployeeId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''GridViewMEDsysStaffs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewMEDsysStaffs As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''UpdatePanelActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonDelete As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonEmployeeDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonEmployeeDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''TextBoxResetPositionCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxResetPositionCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ButtonResetPositionCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonResetPositionCode As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
