'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.EVV

    Partial Public Class ScheduleGeneratorControl

        '''<summary>
        '''Div10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelScheduleGenerator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelScheduleGenerator As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSetting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSetting As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''LabelCompanyName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCompanyName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelVestaAgencyIdCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelVestaAgencyIdCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelVestaAgencyId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelVestaAgencyId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelTransmissionMessageSentToCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTransmissionMessageSentToCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelTransmissionMessageSentTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTransmissionMessageSentTo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelUploadAllUpdatesCaption1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUploadAllUpdatesCaption1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxDays control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxDays As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelUploadAllUpdatesCaption2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUploadAllUpdatesCaption2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelPayPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPayPeriod As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPayPeriodFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPayPeriodFromDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RequiredFieldValidatorPayPeriodFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidatorPayPeriodFromDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''RegularExpressionValidatorPayPeriodFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorPayPeriodFromDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''TextBoxPayPeriodToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPayPeriodToDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RequiredFieldValidatorPayPeriodToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidatorPayPeriodToDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''RegularExpressionValidatorPayPeriodToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidatorPayPeriodToDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''LabelClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelClient As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListClient As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelClientType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelClientType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListClientType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListClientType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelClientGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelClientGroup As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListClientGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListClientGroup As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''UpdatePanelActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonGenerateVestaSchedule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonGenerateVestaSchedule As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonAttendants control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonAttendants As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonClients control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClients As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonAuthorizations control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonAuthorizations As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonNewVisits control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonNewVisits As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonLoggedVisits control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonLoggedVisits As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSyncRecords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSyncRecords As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonClearClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClearClient As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonAutoGenerateEmployeeEVVIDs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonAutoGenerateEmployeeEVVIDs As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonAutoGenerateClientEVVIDs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonAutoGenerateClientEVVIDs As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
