'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.EDISubmission

    Partial Public Class EDICorrectedClaimsControl

        '''<summary>
        '''UpdatePanelEDICorrectedClaims control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelEDICorrectedClaims As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelMedicaidNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMedicaidNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxMedicaidNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxMedicaidNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelClientId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelClientId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxClientId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxClientId As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelIndividual control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelIndividual As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListIndividual control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListIndividual As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelProcedureCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelProcedureCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxProcedureCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxProcedureCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelEDICorrectedClaimsLeftInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelEDICorrectedClaimsLeftInfo As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelDateOfBirth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDateOfBirth As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxDateOfBirth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxDateOfBirth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelGender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelGender As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxGender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxGender As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelProgram control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelProgram As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxProgram control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxProgram As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelStartDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxStartDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEndDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEndDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelBilledHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelBilledHours As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxBilledHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxBilledHours As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelUnitRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUnitRate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxUnitRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxUnitRate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelBilledAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelBilledAmount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxBilledAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxBilledAmount As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelEDICorrectedClaimsRightInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelEDICorrectedClaimsRightInfo As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelContractNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelContractNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxContractNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxContractNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelReceiver control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelReceiver As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListReceiver control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListReceiver As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelDiagnosisCodeOne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDiagnosisCodeOne As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxDiagnosisCodeOne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxDiagnosisCodeOne As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelDiagnosisCodeTwo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDiagnosisCodeTwo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxDiagnosisCodeTwo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxDiagnosisCodeTwo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelDiagnosisCodeThree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDiagnosisCodeThree As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxDiagnosisCodeThree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxDiagnosisCodeThree As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelDiagnosisCodeFour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDiagnosisCodeFour As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxDiagnosisCodeFour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxDiagnosisCodeFour As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelModifierOne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelModifierOne As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxModifierOne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxModifierOne As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelModifierTwo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelModifierTwo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxModifierTwo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxModifierTwo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelModifierThree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelModifierThree As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxModifierThree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxModifierThree As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelModifierFour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelModifierFour As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxModifierFour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxModifierFour As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelClaimFrequencyTypeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelClaimFrequencyTypeCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListClaimFrequencyTypeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListClaimFrequencyTypeCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelClaimNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelClaimNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxClaimNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxClaimNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonDelete As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
