'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.EDISubmission

    Partial Public Class EDIMissingDataControl

        '''<summary>
        '''LabelEDIMissingDataNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEDIMissingDataNote As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelEDIMissingData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelEDIMissingData As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldClientId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldClientId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''GridViewEDIMissingData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewEDIMissingData As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''UpdatePanelButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonIndividual control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonIndividual As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonRefresh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonRefresh As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
