'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.TurboPAS

    Partial Public Class VestaUploadsControl

        '''<summary>
        '''LabelTurboPASVestaUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTurboPASVestaUpload As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelUploadChoice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelUploadChoice As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''CheckBoxIndividualUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBoxIndividualUpload As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''UpdatePanelTurboPASVestaUploadIndividual control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelTurboPASVestaUploadIndividual As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonClientUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClientUpload As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonAuthorizationUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonAuthorizationUpload As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonEmployeeUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonEmployeeUpload As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonVisitsUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonVisitsUpload As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UpdatePanelTurboPASVestaUploadAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelTurboPASVestaUploadAll As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonUploadAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonUploadAll As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonDownload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonDownload As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelCustomMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCustomMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelTurboPASVestaUploadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTurboPASVestaUploadStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelUploadDownloadOperationDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelUploadDownloadOperationDetail As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''GridViewUploadDownloadOperationDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewUploadDownloadOperationDetail As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
