'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.Settings

    Partial Public Class CalendarSetting1

        '''<summary>
        '''UpdatePanelWeelyScheduleHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelWeelyScheduleHeader As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''DropDownListClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListClient As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownListEmployee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListEmployee As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''TextBoxSundayHourMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSundayHourMinute As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxMondayHourMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxMondayHourMinute As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxTuesdayHourMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxTuesdayHourMinute As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxWednesdayHourMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxWednesdayHourMinute As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxThursdayHourMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxThursdayHourMinute As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxFridayHourMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFridayHourMinute As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxSaturdayHourMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSaturdayHourMinute As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxTotalHourMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxTotalHourMinute As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DropDownListScheduleStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListScheduleStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''TextBoxCalendarUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxCalendarUpdateDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TextBoxCalendarUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxCalendarUpdateBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelManage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelManage As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelDayCaptionFirstColumn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDayCaptionFirstColumn As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelInCaptionFirstColumn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelInCaptionFirstColumn As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelOutCaptionFirstColumn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelOutCaptionFirstColumn As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelSundayInOutCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSundayInOutCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ucClockTime_SundayInTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_SundayInTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''ucClockTime_SundayOutTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_SundayOutTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''LabelMondayInOutCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMondayInOutCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ucClockTime_MondayInTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_MondayInTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''ucClockTime_MondayOutTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_MondayOutTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''LabelTuesdayInOutCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTuesdayInOutCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ucClockTime_TuesdayInTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_TuesdayInTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''ucClockTime_TuesdayOutTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_TuesdayOutTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''LabelWednesdayInOutCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelWednesdayInOutCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ucClockTime_WednesdayInTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_WednesdayInTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''ucClockTime_WednesdayOutTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_WednesdayOutTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''LabelDayCaptionSecondColumn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDayCaptionSecondColumn As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelInCaptionSecondColumn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelInCaptionSecondColumn As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelOutCaptionSecondColumn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelOutCaptionSecondColumn As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelThursdayInOutCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelThursdayInOutCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ucClockTime_ThursdayInTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_ThursdayInTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''ucClockTime_ThursdayOutTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_ThursdayOutTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''LabelFridayInOutCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFridayInOutCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ucClockTime_FridayInTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_FridayInTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''ucClockTime_FridayOutTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_FridayOutTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''LabelSaturdayInOutCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSaturdayInOutCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ucClockTime_SaturdayInTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_SaturdayInTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''ucClockTime_SaturdayOutTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucClockTime_SaturdayOutTime As Global.VisitelWeb.Visitel.UserControl.ClockTime

        '''<summary>
        '''UpdatePanelScheduleStartEnd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelScheduleStartEnd As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelSpecialPayrate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSpecialPayrate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSpecialPayrate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSpecialPayrate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelStartDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxStartDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEndDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEndDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelEmptyColumn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEmptyColumn As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxScheduleComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxScheduleComments As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
