'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.Settings

    Partial Public Class CaseWorkerSetting

        '''<summary>
        '''LabelCaseWorkerInformationEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCaseWorkerInformationEntry As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelCaseWorkerInformationEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelCaseWorkerInformationEntry As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFirstName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelLastName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPhone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelFax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFax As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxFax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelMailCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMailCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxMailCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxMailCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelComments As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxComments As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelActionButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelActionButton As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSaveWithConfirmation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSaveWithConfirmation As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelSearchCaseWorkerInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchCaseWorkerInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelSearchByFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchByFirstName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSearchByFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSearchByFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSearchByLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchByLastName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSearchByLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSearchByLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSearchByPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchByPhone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSearchByPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSearchByPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelSearch As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Div20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div20 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelCaseWorkerInformationList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCaseWorkerInformationList As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelCaseWorkerInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelCaseWorkerInformation As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldCaseWorkerId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldCaseWorkerId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsNew As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsSearched control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsSearched As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''GridViewCaseWorkerInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewCaseWorkerInformation As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
