'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.Settings

    Partial Public Class CountySetting

        '''<summary>
        '''LabelCountyInformationEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCountyInformationEntry As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelCountyInformationEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelCountyInformationEntry As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelCountyCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCountyCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxCountyCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxCountyCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelCountyName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCountyName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxCountyName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxCountyName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelActionButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelActionButton As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelSearchCountyInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchCountyInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelSearchByCountyName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchByCountyName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSearchByCountyName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSearchByCountyName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelSearch As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Div20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div20 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelCountyInformationList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCountyInformationList As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelCountyInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelCountyInformation As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldIdCountyId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIdCountyId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsNew As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsSearched control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsSearched As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''GridViewCountyInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewCountyInformation As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
