'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.Settings

    Partial Public Class DischargeReasonSetting

        '''<summary>
        '''LabelDischargeReasonInformationEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDischargeReasonInformationEntry As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelDischargeReasonInformationEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelDischargeReasonInformationEntry As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''UpdatePanelActionButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelActionButton As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelSearchDischargeReasonInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchDischargeReasonInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelSearchByName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchByName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSearchByName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSearchByName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSearchByStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchByStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListSearchByStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListSearchByStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''UpdatePanelSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelSearch As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Div20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div20 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelDischargeReasonInformationList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDischargeReasonInformationList As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelDischargeReasonInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelDischargeReasonInformation As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldIdNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIdNumber As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsNew As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsSearched control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsSearched As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''GridViewDischargeReasonInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewDischargeReasonInformation As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
