'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.Settings

    Partial Public Class DoctorSetting

        '''<summary>
        '''LabelDoctorInformationEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDoctorInformationEntry As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelDoctorInformationEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelDoctorInformationEntry As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelUPinNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUPinNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxUPinNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxUPinNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelLicNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelLicNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxLicNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxLicNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFirstName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelLastName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSuite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSuite As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSuite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSuite As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListCity As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListState As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelZip As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxZip As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPhone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelFax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFax As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxFax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''UpdatePanelActionButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelActionButton As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelSearchDoctorInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchDoctorInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelSearchByUpinNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchByUpinNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSearchByUpinNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSearchByUpinNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSearchByLicNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchByLicNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSearchByLicNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSearchByLicNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelSearch As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Div20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div20 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelDoctorInformationList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelDoctorInformationList As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelDoctorInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelDoctorInformation As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldDoctorId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldDoctorId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsNew As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsSearched control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsSearched As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''GridViewDoctorInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewDoctorInformation As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
