'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.Settings

    Partial Public Class HospitalStaySetting

        '''<summary>
        '''LabelHospitalStayInformationList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelHospitalStayInformationList As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelHospitalStay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelHospitalStay As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''GridViewHospitalStay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewHospitalStay As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''ButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
