'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.Settings

    Partial Public Class MaritalStatusSetting

        '''<summary>
        '''LabelMaritalStatusInformationEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMaritalStatusInformationEntry As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSettingMaritalStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingMaritalStatus As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''UpdatePanelMaritalStatusInformationEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelMaritalStatusInformationEntry As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''UpdatePanelActionButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelActionButton As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelSearchMaritalStatusInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchMaritalStatusInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelSearchByName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchByName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSearchByName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSearchByName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelSearch As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Div20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div20 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelMaritalStatusInformationList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMaritalStatusInformationList As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanelMaritalStatusInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelMaritalStatusInformation As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldIdNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIdNumber As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsNew As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldIsSearched control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldIsSearched As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''GridViewMaritalStatusInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewMaritalStatusInformation As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
