'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.PayPeriod

    Partial Public Class CareSummaryPayPeriodDetailControl

        '''<summary>
        '''UpdatePanelHospitalizedIndividuals control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelHospitalizedIndividuals As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''SqlDataSourceCareSummaryPayPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceCareSummaryPayPeriod As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''GridViewCareSummaryPayPeriodDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewCareSummaryPayPeriodDetail As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''UpdatePanelTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelTime As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelTotalTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTotalTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxTotalTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxTotalTime As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
