'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.PayPeriod

    Partial Public Class PayPeriodDetailControl

        '''<summary>
        '''Div10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LabelPayPeriodDetailInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPayPeriodDetailInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSetting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSetting As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''UpdatePanelPayPeriodDetailFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelPayPeriodDetailFilter As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonViewError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonViewError As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelSearchByIndividual control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchByIndividual As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListSearchByIndividual control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListSearchByIndividual As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ButtonAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonAll As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelCalendarIdCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCalendarIdCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListCalendarId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListCalendarId As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SqlDataSourceCalendarId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceCalendarId As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''LabelServiceDateCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelServiceDateCaption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListServiceDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListServiceDate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SqlDataSourceServiceDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceServiceDate As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''UpdatePanelPayPeriodDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelPayPeriodDetail As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''HiddenFieldClientId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldClientId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldEmployeeId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldEmployeeId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldStartDate As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldEndDate As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HiddenFieldScheduleId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenFieldScheduleId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''GridViewPayPeriodDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewPayPeriodDetail As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''UpdatePanelActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonPopulateCareSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonPopulateCareSummary As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonIndividualDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonIndividualDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonEmployeeDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonEmployeeDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelTotalTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTotalTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxTotalTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxTotalTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CheckBoxSavePrompt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBoxSavePrompt As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ButtonHospitalizedIndividuals control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonHospitalizedIndividuals As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
