'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel

    Partial Public Class UnauthorizedAccess

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As VisitelWeb.Visitel.VisitelMasterPage
            Get
                Return CType(MyBase.Master, VisitelWeb.Visitel.VisitelMasterPage)
            End Get
        End Property
    End Class
End Namespace
