'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel

    Partial Public Class VisitelMasterPageBlank

        '''<summary>
        '''PopupPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PopupPage As Global.System.Web.UI.HtmlControls.HtmlHead

        '''<summary>
        '''cphPopupHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cphPopupHead As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''FormVisitelPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormVisitelPopup As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ScriptManagerPopupPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManagerPopupPage As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''divErrMesg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divErrMesg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblErrMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divInfoMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divInfoMsg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cphMain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cphMain As Global.System.Web.UI.WebControls.ContentPlaceHolder
    End Class
End Namespace
