'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel

    Partial Public Class VisitelMasterPage

        '''<summary>
        '''ParentPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ParentPage As Global.System.Web.UI.HtmlControls.HtmlHead

        '''<summary>
        '''cphHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cphHead As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''FormVisitel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormVisitel As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ScriptManagerParentPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManagerParentPage As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''htHeaderTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents htHeaderTitle As Global.VisitelWeb.Visitel.UserControl.Header

        '''<summary>
        '''lblPageHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageHeader As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListThemeSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListThemeSelect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUser As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ucMenuAdapter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucMenuAdapter As Global.VisitelWeb.Visitel.UserControl.MenuAdapter

        '''<summary>
        '''upnlMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnlMsg As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''divErrMesg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divErrMesg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblErrMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divInfoMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divInfoMsg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ContentMain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContentMain As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''FooterTitle1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FooterTitle1 As Global.VisitelWeb.Visitel.UserControl.Footer

        '''<summary>
        '''Timeout1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Timeout1 As Global.TSC.Timeout.Timeout

        '''<summary>
        '''UCChangePassword1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UCChangePassword1 As Global.VisitelWeb.Visitel.UserControl.UCChangePassword
    End Class
End Namespace
