'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.EDICentral

    Partial Public Class BillingProviderControl

        '''<summary>
        '''UpdatePanelBillingProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelBillingProvider As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''UserControlEditSettingBillingProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingBillingProvider As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''LabelBillingProviderId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelBillingProviderId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelEntityIDCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEntityIDCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListEntityIdCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListEntityIdCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelEntityTypeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEntityTypeQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListEntityTypeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListEntityTypeQualifier As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelLastOrOrgName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelLastOrOrgName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxLastOrOrgName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxLastOrOrgName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelFirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFirst As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxFirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFirst As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelMiddle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMiddle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxMiddle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxMiddle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPrefix As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPrefix As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSuffix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSuffix As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSuffix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSuffix As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelBillingProviderUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelBillingProviderUpdateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxBillingProviderUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxBillingProviderUpdateDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelBillingProviderUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelBillingProviderUpdateBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxBillingProviderUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxBillingProviderUpdateBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxState As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelZip As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxZip As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelReferenceIDQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelReferenceIDQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListReferenceIdQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListReferenceIdQualifier As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelEINOrSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEINOrSSN As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEINOrSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEINOrSSN As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelIDCodeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelIDCodeQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListIdCodeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListIdCodeQualifier As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelNPI control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelNPI As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxNPI control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxNPI As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelContractNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxContractNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelBillingProviderControlActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelBillingProviderControlActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonBillingProviderClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonBillingProviderClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonBillingProviderSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonBillingProviderSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonBillingProviderDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonBillingProviderDelete As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
