'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.EDICentral

    Partial Public Class FunctionalGroupHeaderControl

        '''<summary>
        '''UpdatePanelFunctionalGroupHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelFunctionalGroupHeader As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelFunctionalGroupHeaderId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFunctionalGroupHeaderId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSettingFunctionalGroupHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingFunctionalGroupHeader As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''LabelFunctionalIdentifierCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFunctionalIdentifierCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxFunctionalIdentifierCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFunctionalIdentifierCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelApplicationSenderCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelApplicationSenderCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxApplicationSenderCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxApplicationSenderCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelApplicationReceiverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelApplicationReceiverCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListApplicationReceiverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListApplicationReceiverCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SqlDataSourceApplicationReceiverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceApplicationReceiverCode As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''LabelGroupControlNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelGroupControlNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxGroupControlNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxGroupControlNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelResponsibleAgencyCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelResponsibleAgencyCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxResponsibleAgencyCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxResponsibleAgencyCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelIndustryIdentifierCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelIndustryIdentifierCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxIndustryIdentifierCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxIndustryIdentifierCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelContractNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxContractNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUpdateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxUpdateDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUpdateBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxUpdateBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelFunctionalGroupHeaderControlActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelFunctionalGroupHeaderControlActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonFunctionalGroupHeaderClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonFunctionalGroupHeaderClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonFunctionalGroupHeaderSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonFunctionalGroupHeaderSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonFunctionalGroupHeaderDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonFunctionalGroupHeaderDelete As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
