'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.EDICentral

    Partial Public Class InterchangeControlHeaderControl

        '''<summary>
        '''UpdatePanelInterchangeControlHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelInterchangeControlHeader As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''LabelInterchangeControlHeaderId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelInterchangeControlHeaderId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserControlEditSettingInterchangeControlHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingInterchangeControlHeader As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''LabelAuthorizationInformationQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAuthorizationInformationQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListAuthorizationInformationQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListAuthorizationInformationQualifier As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelAuthorizationInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAuthorizationInformation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAuthorizationInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAuthorizationInformation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSecurityInformationQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSecurityInformationQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListSecurityInformationQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListSecurityInformationQualifier As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelSecurityInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSecurityInformation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSecurityInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSecurityInformation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelInterchangeIDQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelInterchangeIDQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListInterchangeIdQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListInterchangeIdQualifier As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelSubmitterId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSubmitterId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSubmitterId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSubmitterId As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelReceiverId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelReceiverId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxReceiverId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxReceiverId As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelControlVersionId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelControlVersionId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxControlVersionId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxControlVersionId As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelControlNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelControlNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxControlNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxControlNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelAcknowledgementRequested control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAcknowledgementRequested As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListAcknowledgementRequested control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListAcknowledgementRequested As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelUsageIndicator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUsageIndicator As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListUsageIndicator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListUsageIndicator As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelContractNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxContractNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUpdateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxUpdateDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUpdateBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxUpdateBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelInterchangeControlHeaderActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelInterchangeControlHeaderActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonInterchangeControlHeaderClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonInterchangeControlHeaderClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonInterchangeControlHeaderSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonInterchangeControlHeaderSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonInterchangeControlHeaderDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonInterchangeControlHeaderDelete As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
