'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.EDICentral

    Partial Public Class RenderingProviderControl

        '''<summary>
        '''UpdatePanelRenderingProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelRenderingProvider As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''UserControlEditSettingRenderingProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingRenderingProvider As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''LabelRenderingProviderId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelRenderingProviderId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelEntityIDCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEntityIDCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListEntityIdCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListEntityIdCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelEntityTypeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEntityTypeQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListEntityTypeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListEntityTypeQualifier As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelLastOrOrgName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelLastOrOrgName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxLastOrOrgName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxLastOrOrgName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelFirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFirst As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxFirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFirst As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelMiddle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMiddle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxMiddle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxMiddle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPrefix As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPrefix As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSuffix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSuffix As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSuffix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSuffix As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelReferringProviderUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelReferringProviderUpdateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxReferringProviderUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxReferringProviderUpdateDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelReferringProviderUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelReferringProviderUpdateBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxReferringProviderUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxReferringProviderUpdateBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxState As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelZip As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxZip As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelReferenceIDQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelReferenceIDQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListReferenceIdQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListReferenceIdQualifier As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelEINOrSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEINOrSSN As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEINOrSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEINOrSSN As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelIDCodeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelIDCodeQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListIdCodeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListIdCodeQualifier As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelRenderingProviderIdentifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelRenderingProviderIdentifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxRenderingProviderIdentifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxRenderingProviderIdentifier As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelContractNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxContractNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelProviderCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelProviderCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListProviderCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListProviderCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SqlDataSourceProviderCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceProviderCode As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''LabelRefIdQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelRefIdQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListRefIdQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListRefIdQualifier As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SqlDataSourceRefIdQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceRefIdQualifier As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''LabelTaxonomyCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTaxonomyCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxTaxonomyCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxTaxonomyCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelRenderingProviderActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelRenderingProviderActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonRenderingProviderClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonRenderingProviderClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonRenderingProviderSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonRenderingProviderSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonRenderingProviderDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonRenderingProviderDelete As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
