'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.EDICentral

    Partial Public Class SubmitterControl

        '''<summary>
        '''UpdatePanelSubmitter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelSubmitter As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''UserControlEditSettingSubmitter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingSubmitter As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''LabelSubmitterId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSubmitterId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelEntityIdentifierCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEntityIdentifierCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListEntityIdentifierCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListEntityIdentifierCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelEntityTypeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEntityTypeQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListEntityTypeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListEntityTypeQualifier As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelNameLastOrOrganizationName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelNameLastOrOrganizationName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxNameLastOrOrganizationName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxNameLastOrOrganizationName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFirstName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelMiddleName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxMiddleName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPrefix As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPrefix As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSuffix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSuffix As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSuffix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSuffix As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelPrimaryIdentificationNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPrimaryIdentificationNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPrimaryIdentificationNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPrimaryIdentificationNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelContractName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelContractName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxContractName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxContractName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPhone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelContractNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxContractNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUpdateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxUpdateDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelUpdateBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxUpdateBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelSubmitterActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelSubmitterActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSubmitterClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSubmitterClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSubmitterSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSubmitterSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSubmitterDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSubmitterDelete As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
