'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Visitel.UserControl.EDICentral

    Partial Public Class SubscriberInfoControl

        '''<summary>
        '''UpdatePanelSubscriberInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelSubscriberInfo As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''UserControlEditSettingSubscriberInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlEditSettingSubscriberInfo As Global.VisitelWeb.Visitel.UserControl.EditSetting

        '''<summary>
        '''LabelSubscriberInfoId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSubscriberInfoId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LabelPayerResponsibilitySequenceNumberCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelPayerResponsibilitySequenceNumberCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListPayerResponsibilitySequenceNumberCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListPayerResponsibilitySequenceNumberCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelRelationshipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelRelationshipCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListRelationshipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListRelationshipCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelGroupOrPolicyNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelGroupOrPolicyNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxGroupOrPolicyNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxGroupOrPolicyNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelGroupOrPlanName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelGroupOrPlanName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxGroupOrPlanName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxGroupOrPlanName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelInsuranceTypeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelInsuranceTypeCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxInsuranceTypeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxInsuranceTypeCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelClaimFilingIndicatorCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelClaimFilingIndicatorCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DropDownListClaimFilingIndicatorCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownListClaimFilingIndicatorCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LabelEntityIdentificationCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEntityIdentificationCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEntityIdentificationCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEntityIdentificationCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelEntityTypeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelEntityTypeQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxEntityTypeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxEntityTypeQualifier As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelIdCodeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelIdCodeQualifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxIdCodeQualifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxIdCodeQualifier As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelContractNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxContractNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSubscriberInfoUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSubscriberInfoUpdateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSubscriberInfoUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSubscriberInfoUpdateDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LabelSubscriberInfoUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSubscriberInfoUpdateBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBoxSubscriberInfoUpdateBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSubscriberInfoUpdateBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UpdatePanelSubmitterActionButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanelSubmitterActionButtons As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ButtonSubscriberInfoClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSubscriberInfoClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSubscriberInfoSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSubscriberInfoSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ButtonSubscriberInfoDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSubscriberInfoDelete As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
